# Generated by Django 4.2.3 on 2023-08-13 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_place_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='owner',
        ),
    ]
