# Generated by Django 4.2.3 on 2023-08-13 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticket_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='is_free',
        ),
        migrations.AlterField(
            model_name='place',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie'),
        ),
    ]
