# Generated by Django 4.2.3 on 2023-08-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_place_is_free_alter_place_ticket_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
