# Generated by Django 4.2.3 on 2023-08-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.AlterField(
            model_name='movie',
            name='label',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.CharField(max_length=30),
        ),
    ]
