# Generated by Django 4.2.3 on 2023-08-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_movie_image_alter_movie_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=1, upload_to='movies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='label',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
