# Generated by Django 4.2.3 on 2023-08-14 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ticket'),
        ),
    ]
